---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-ceph-rgw-global
  layeringDefinition:
    abstract: false
    layer: global
  labels:
    name: ucp-ceph-rgw-global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.ceph-rgw
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ceph.ceph-rgw
      dest:
        path: .values.images.tags

    # IP addresses
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .storage.ceph.public_cidr
      dest:
        path: .values.network.public
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .storage.ceph.cluster_cidr
      dest:
        path: .values.network.cluster

    # Endpoints
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ceph.object_store
      dest:
        path: .values.endpoints.object_store
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ceph.ceph_mon
      dest:
        path: .values.endpoints.ceph_mon

    # Credentials
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ceph.swift.keystone
      dest:
        path: .values.endpoints.identity.auth.swift

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.swift.password
      src:
        schema: deckhand/Passphrase/v1
        name: ceph_swift_keystone_password
        path: .

data:
  chart_name: ucp-ceph-rgw
  release: ucp-ceph-rgw
  namespace: ucp
  wait:
    timeout: 900
    labels:
      release_group: clcp-ucp-ceph-rgw
    resources:
      - type: deployment
        min_ready: 2
      - type: job
    native:
      enabled: false
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: clcp-ucp-ceph-rgw
  test:
    enabled: true
  values:
    manifests:
      job_bootstrap: true
    labels:
      job:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
      rgw:
        node_selector_key: ceph-rgw
        node_selector_value: enabled
    endpoints:
      identity:
        namespace: ucp
      object_store:
        namespace: ucp
      ceph_mon:
        namespace: ceph
    deployment:
      ceph: true
      rgw_keystone_user_and_endpoints: true
    bootstrap:
      enabled: false
    pod:
      affinity:
        anti:
          type:
            default: preferredDuringSchedulingIgnoredDuringExecution
      replicas:
        rgw: 3
    conf:
      rgw_ks:
        enabled: true
        config:
          rgw_keystone_accepted_roles: "admin, _member_, member"
    ceph_client:
      configmap: ceph-etc
    secrets:
      keyrings:
        admin: pvc-ceph-client-key
  dependencies:
    - ceph-htk
...
